on: 
  workflow_dispatch:
  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - run: |
        echo "last commit: ${{ github.event.head_commit.message }}" 
