on: 
  workflow_dispatch:
  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Set Run Number
        run: $env.GITHUB_RUN_NUMBER = 1

      - name: Output Run Number
        run: echo ${{ github.run_number }}
