name: test passing in values


on:
  push:
    branches:
      - main

jobs:
  read_file:
    runs-on: ubuntu-latest
    steps:
      - name: Read VERSION file
        id: vars
        run: echo ::set-output name=version::$(cat ivan)
      - name: Test output
        run: echo ${{ steps.vars.outputs.version }}