name: test passing in values


on:
  push:
    branches:
      - main

jobs:
  read_file:
    runs-on: ubuntu-latest
    steps:
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat ivan)"