name: test passing in values


on:
  push:
    branches:
      - main

jobs:
  read_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: set_var
        run: |
          content=`cat .github/workflows/build_info`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).name}}"
          echo "${{fromJson(steps.set_var.outputs.packageJson).age}}"
      # - name: Read VERSION file
      #   id: vars
      #   run: echo ::set-output name=version::$(cat .github/workflows/build_info)
      # -name: read Json
      #   id: json
      #     run: |
      #       # the following lines are only required for multi line json
      #       content="${content//'%'/'%25'}"
      #       content="${content//$'\n'/'%0A'}"
      #       content="${content//$'\r'/'%0D'}"
      #       # end of optional handling for multi line json